// test-apps/hosting-ssr-nuxt/app/pages/headers-test.vue
<template>
  <main>
    <h2>Route rule headers</h2>
    <p>
      <code>nuxt.config.ts</code> applies <code>x-stress-test: on</code> + <code>cache-control: s-maxage=120, stale-while-revalidate=60</code>{' '}
      to <code>/headers-test</code>. Open DevTools → Network → reload to verify.
    </p>
    <p :style="{ marginTop: '16px', fontSize: '13px', color: '#666' }">Source: <code>nuxt.config.ts → routeRules</code></p>
  </main>
</template>

// test-apps/hosting-ssr/src/app/headers-test/page.tsx
export const dynamic = 'force-dynamic';

export default function HeadersTestPage() {
  return (
    <main>
      <h2>next.config headers()</h2>
      <p>
        <code>next.config.ts</code> applies <code>x-stress-test: on</code> + custom <code>Cache-Control</code> to{' '}
        <code>/headers-test</code>. Open DevTools → Network → reload to verify.
      </p>
      <p style={{ marginTop: 16, fontSize: 13, color: '#666' }}>Source: <code>next.config.ts → headers()</code></p>
    </main>
  );
}
