// test-apps/hosting-ssr-nuxt/app/pages/server-action.vue
<script setup lang="ts">
import { ref } from 'vue';

const counter = ref<number | null>(null);

async function fetchValue() {
  const r = await fetch('/api/probe/counter');
  const j = await r.json();
  counter.value = j.value;
}

async function increment() {
  const r = await fetch('/api/probe/counter', { method: 'POST' });
  const j = await r.json();
  counter.value = j.value;
}

async function reset() {
  const r = await fetch('/api/probe/counter', { method: 'DELETE' });
  const j = await r.json();
  counter.value = j.value;
}

fetchValue();
</script>

<template>
  <main>
    <h2>Server-side counter</h2>
    <p>
      An in-memory counter on the server. Each Lambda instance has its own copy — refresh on a cold start resets it.
    </p>
    <p :style="{ fontSize: '22px' }">Counter: <strong>{{ counter ?? '(loading)' }}</strong></p>
    <button :style="{ padding: '6px 14px', marginRight: '8px' }" @click="increment">+1</button>
    <button :style="{ padding: '6px 14px' }" @click="reset">reset</button>
    <p :style="{ marginTop: '16px', fontSize: '13px', color: '#666' }">Source: <code>app/pages/server-action.vue</code> + <code>server/api/probe/counter.*.ts</code></p>
  </main>
</template>

// test-apps/hosting-ssr/src/app/server-action/page.tsx
import { revalidatePath } from 'next/cache';

const g = globalThis as unknown as { __counter?: { value: number } };
function getCounter() {
  if (!g.__counter) g.__counter = { value: 0 };
  return g.__counter;
}

async function increment() {
  'use server';
  getCounter().value++;
  revalidatePath('/server-action');
}

async function reset() {
  'use server';
  getCounter().value = 0;
  revalidatePath('/server-action');
}

export const dynamic = 'force-dynamic';

export default function ServerActionPage() {
  const c = getCounter();
  return (
    <main>
      <h2>Server Action + revalidatePath</h2>
      <p>
        Form-action posts to a server function. Counter is in-memory per Lambda instance — refreshing on a cold start
        resets it. Click <code>+1</code>, then <code>reset</code>.
      </p>
      <p style={{ fontSize: 22 }}>
        Counter: <strong data-testid="counter-value">{c.value}</strong>
      </p>
      <form action={increment} style={{ display: 'inline' }}>
        <button style={{ padding: '6px 14px', marginRight: 8 }}>+1</button>
      </form>
      <form action={reset} style={{ display: 'inline' }}>
        <button style={{ padding: '6px 14px' }}>reset</button>
      </form>
      <p style={{ marginTop: 16, fontSize: 13, color: '#666' }}>Source: <code>app/server-action/page.tsx</code></p>
    </main>
  );
}
