// test-apps/hosting-ssr/src/app/streaming/page.tsx
import { Suspense } from 'react';

async function Slow({ ms, label }: { ms: number; label: string }) {
  await new Promise((r) => setTimeout(r, ms));
  return (
    <div style={{ padding: 8, border: '1px solid #ccc', marginBottom: 8 }}>
      <strong>{label}</strong> resolved at {new Date().toISOString()} (after {ms}ms)
    </div>
  );
}

export const dynamic = 'force-dynamic';

export default function StreamingPage() {
  return (
    <main>
      <h2>React Streaming Suspense</h2>
      <p>
        Three deferred async children flush independently. TTFB should be much smaller than the total render time.
        Open DevTools → Network → reload, expand the document row to see chunk timings.
      </p>
      <p>Page started rendering at {new Date().toISOString()}</p>
      <Suspense fallback={<div>fast (1s) loading…</div>}>
        <Slow ms={1000} label="fast (1s)" />
      </Suspense>
      <Suspense fallback={<div>medium (2s) loading…</div>}>
        <Slow ms={2000} label="medium (2s)" />
      </Suspense>
      <Suspense fallback={<div>slow (3s) loading…</div>}>
        <Slow ms={3000} label="slow (3s)" />
      </Suspense>
      <p style={{ marginTop: 16, fontSize: 13, color: '#666' }}>Source: <code>app/streaming/page.tsx</code></p>
    </main>
  );
}

// test-apps/hosting-ssr-nuxt/app/pages/streaming.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';

const fast = ref('loading…');
const medium = ref('loading…');
const slow = ref('loading…');

onMounted(() => {
  setTimeout(() => (fast.value = `fast (1s) resolved at ${new Date().toISOString()}`), 1000);
  setTimeout(() => (medium.value = `medium (2s) resolved at ${new Date().toISOString()}`), 2000);
  setTimeout(() => (slow.value = `slow (3s) resolved at ${new Date().toISOString()}`), 3000);
});

const renderTime = new Date().toISOString();
</script>

<template>
  <main>
    <h2>Streaming / progressive hydration</h2>
    <p>
      Three deferred children (1s, 2s, 3s) hydrate progressively after first paint.
    </p>
    <p>Page first painted at {{ renderTime }}</p>
    <div :style="{ padding: '8px', border: '1px solid #ccc', marginBottom: '8px' }"><strong>Fast:</strong> {{ fast }}</div>
    <div :style="{ padding: '8px', border: '1px solid #ccc', marginBottom: '8px' }"><strong>Medium:</strong> {{ medium }}</div>
    <div :style="{ padding: '8px', border: '1px solid #ccc', marginBottom: '8px' }"><strong>Slow:</strong> {{ slow }}</div>
    <p :style="{ marginTop: '16px', fontSize: '13px', color: '#666' }">Source: <code>app/pages/streaming.vue</code></p>
  </main>
</template>
